export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const CLEAR = "CLEAR";

export const ADD_TEACHER = "ADD_TEACHER";
export const ADD_STUDENT = "ADD_STUDENT";
export const ADD_SUBJECT = "ADD_SUBJECT";
export const ADD_ADMIN = "ADD_ADMIN";

export const FETCH_ALL_TEACHERS = "FETCH_ALL_TEACHERS";
export const FETCH_ALL_STUDENTS = "FETCH_ALL_STUDENTS";
export const FETCH_ALL_SUBJECTS = "FETCH_ALL_SUBJECTS";

export const UPDATE_TEACHER = "UPDATE_TEACHER";
export const UPDATE_TEACHER_PASSWORD = "UPDATE_TEACHER_PASSWORD";
export const MARK_ATTENDANCE = "MARK_ATTENDANCE";
export const ADD_ATTENDANCE = "ADD_ATTENDANCE";
export const MARK_TEST = "MARK_TEST";
export const ADD_TEST = "ADD_TEST";
export const SHOW_MARKS = "SHOW_MARKS";
export const SHOW_ATTENDANCE = "SHOW_ATTENDANCE";

export const UPDATE_STUDENT = "UPDATE_STUDENT";
export const UPDATE_STUDENT_PASSWORD = "UPDATE_STUDENT_PASSWORD";
export const SHOW_TEST_MARKS = "SHOW_TEST_MARKS";
export const SHOW_STUDENT_SUBJECTS = "SHOW_STUDENT_SUBJECTS";
export const SHOW_STUDENT_ATTENDANCE = "SHOW_STUDENT_ATTENDANCE";